### ISSUE TITLE
iPhone X, Xr, XMax - inputView overlap with the safeAreaLayoutGuide

### ISSUE THREAD

**Issue by SyneKanetiya** [JeaSungLEE/JSGrowingTextView#2]
![simulator screen shot - iphone xr - 2019-02-01 at 17 06 58](https://user-images.githubusercontent.com/47214099/52120942-f9601a00-2643-11e9-90db-cb35bdc0fcec.png)

**Comment by JeaSungLEE** [comment]
I've fixed safearea issue in the Example Project.
Please check this commit..
(f3258542ffd063f098f3378a6b53ab3c849ff981)

thx.
